name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Configure AWS credentials
      run: echo -e "[default]\naws_access_key_id=${AKIAXMI4EDC7BNKQRR4R}\naws_secret_access_key=${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}" > ~/.aws/credentials

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      run: terraform apply -auto-approve
